language: cpp

dist: trusty

sudo: false

notifications:
  email: false

env:
  global:
    - SCONS_CACHE=$HOME/.scons_cache
    - SCONS_CACHE_LIMIT=1024
    - OPTIONS="verbose=yes progress=no gdnative_wrapper=yes"
    - GODOT_REPO_URL="https://github.com/godotengine/godot"
    - GODOT_DIR="godot"
cache:
  directories:
    - $SCONS_CACHE

matrix:
  include:
    - env: GODOT_TARGET=x11 TOOLS=yes CACHE_NAME=${GODOT_TARGET}-gcc-tools"
      os: linux
      compiler: gcc
    - env: GODOT_TARGET=x11 TOOLS=no CACHE_NAME=${GODOT_TARGET}-clang"
      os: linux
      compiler: clang
    # - env: GODOT_TARGET=windows TOOLS=yes CACHE_NAME=${GODOT_TARGET}-gcc-tools
    #   os: linux
    #   compiler: gcc
    - env: GODOT_TARGET=android TOOLS=no CACHE_NAME=${GODOT_TARGET}-gcc
      os: linux
      compiler: gcc
    - env: GODOT_TARGET=osx TOOLS=yes CACHE_NAME=${GODOT_TARGET}-clang-tools
      os: osx
      osx_image: xcode9.3
      compiler: clang
    - env: GODOT_TARGET=iphone TOOLS=no CACHE_NAME=${GODOT_TARGET}-clang
      os: osx
      osx_image: xcode9.3
      compiler: clang
    - env: GODOT_TARGET=server TOOLS=no CACHE_NAME=${GODOT_TARGET}-clang"
      os: linux
      compiler: clang

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-5.0
    packages:
      - build-essential
      - scons
      - pkg-config
      - libx11-dev
      - libxcursor-dev
      - libxi-dev
      - libxinerama-dev
      - libxrandr-dev
      - libgl1-mesa-dev
      - libglu1-mesa-dev
      - libasound2-dev
      - libfreetype6-dev

install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ] && [ "$GODOT_TARGET" = "android" ]; then
      misc/travis/android-tools-linux.sh;
    fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then
      misc/travis/scons-local-osx.sh;
    fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ] && [ "$GODOT_TARGET" = "android" ]; then
      misc/travis/android-tools-osx.sh;
    fi

before_script:
  - if [ "$GODOT_TARGET" = "android" ]; then
      export ANDROID_HOME=$TRAVIS_BUILD_DIR/godot-dev/build-tools/android-sdk;
      export ANDROID_NDK_ROOT=$TRAVIS_BUILD_DIR/godot-dev/build-tools/android-ndk;
    fi
  # - if [ "$GODOT_TARGET" = "windows" ]; then
  #     misc/travis/windows-tools-linux.sh;
  #   fi

  # - cd
  # - export PATH=$PATH:$(pwd)/mxe/usr/bin
  # - export MINGW32_PREFIX=$(pwd)/mxe/usr/bin/i686-w64-mingw32.static-
  # - export MINGW64_PREFIX=$(pwd)/mxe/usr/bin/x86_64-w64-mingw32.static-

  - cd
  - git clone --depth=1 "$GODOT_REPO_URL"
  - cd "godot/"
  - ln -s $TRAVIS_BUILD_DIR "modules/anl"

script:
  - scons -j3 CC=$CC CXX=$CXX platform=$GODOT_TARGET TOOLS=$TOOLS $OPTIONS;
